---
title: "ggplot2"
output: html_document
---


## Scatter Plots

```{r echo=FALSE}
ggplot(data=mpg) + 
  geom_point(mapping = aes(x=displ, y=hwy, color = cyl), position = 'jitter')
```

##Using Facets

```{r}
ggplot(data=mpg) + 
  geom_point(mapping = aes(x=displ, y=hwy)) +
  facet_grid(drv~cyl)

```

```{r echo=FALSE}
ggplot(data=mpg) + 
  geom_smooth(mapping = aes(x=displ, y=hwy, color = cyl, linetype=drv))
```


```{r echo=FALSE}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color=class)) + 
  geom_smooth()
```


```{r echo=FALSE}
ggplot(data=diamonds) +
  geom_bar(mapping = aes(x=cut, fill=color), position='identity')
# try position dodge and fill
```


```{r echo=FALSE}
ggplot(data=diamonds) +
  geom_bar(mapping = aes(x=cut, y=stat(prop), group = 1))
```



```{r echo=FALSE}
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot() +
  coord_flip()
```



```{r echo=FALSE}
ggplot(diamonds, aes(x = "", fill = cut)) + 
  geom_bar() +
  coord_polar(theta = "y")
```

```
