---
title: "marketing_prediction"
author: "Kevin"
date: "31 May 2021"
output: html_document
---

```{r}
library(tidyverse)
library(data.table)
```

```{r}
marketing_raw <- fread('data/marketing_data.csv', colClasses = c('Education'='factor', 'Marital_Status'='factor',
                                                                 'Country'='factor'))
head(marketing_raw)
```


```{r}
marketing_proc <- marketing_raw %>% 
  mutate(Dt_Customer = mdy(Dt_Customer),  
         Income = as.double(str_replace_all(Income, "[$,]", "")),
         Age=2014-Year_Birth,
         People_at_home = if_else(Marital_Status %in% c('Married','Together'), Kidhome+Teenhome+2, Kidhome+Teenhome+1)) %>%
  mutate_at(vars(Income),~ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x))
head(marketing_proc)
```

## Baseline Model

```{r}
base <- glm(data = marketing_proc, Response ~ Age + Income + Kidhome + Teenhome + Recency, family = 'binomial' )
summary(base)
table(fitted.values(base), marketing_proc$Response)
```